### ISSUE TITLE
TIM_FLAG_UPDATE never set

### ISSUE THREAD

**Issue by ipa64** [evilwombat/stm32f103_fastNP#3]
Hi, 
I need some help.
It never get the flag TIM_FLAG_UPDATE, so it stay here:   
        while (!__HAL_TIM_GET_FLAG(&htimer2, TIM_FLAG_UPDATE));

Thank

stm32f103c8t6 bluepill china clone board

**Comment by evilwombat** [comment]
Sorry, I don't get notifications about issues for some reason?

I'm using the same chip you are, and very likely the same board too. Did you remember to call ws2812_init()? This kicks off the timer2 stuff. Does the demo code work as-is?

**Comment by ipa64** [comment]
Hi,
Oups I forgot about this issue, finally I used another way to drive my NeoPixel 
Thank you
